apiVersion: v1
kind: Service
metadata:
  name: catanatron-service
  labels:
    app: catanatron
spec:
  type: LoadBalancer
  selector:
    app: catanatron
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5001
